simple_model:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    base_to_second_joint_position_controller:
        type: velocity_controllers/JointVelocityController
        joint: base_to_second_joint
        pid: {p: 10.0, i: 0.01, d: 0.0}

    base_to_third_joint_position_controller:
        type: velocity_controllers/JointVelocityController
        joint: base_to_third_joint
        pid: {p: 10.0, i: 0.01, d: 0.0}
